---
title: "asymmetry-priors"
author: "mht"
date: "August 12, 2015"
output: html_document
---
Priors
```{r helpers}
library(coda)
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
HPDhi<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
HPDlo<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}

```



By Item

```{r priors2.byItem}
d1<-read.csv("~/Documents/research/generics/manuscript/model-results/generics-asym-priorByItem-incrmh100000_burn50000a.csv")
d2<-read.csv("~/Documents/research/generics/manuscript/model-results/generics-asym-priorByItem-incrmh100000_burn50000b.csv")
d3<-read.csv("~/Documents/research/generics/manuscript/model-results/generics-asym-priorByItem-incrmh100000_burn50000c.csv")

samples = 50000
d<-bind_rows(d1,d2,d3)




d.tidy <- d

# d.tidy <- d.tidy %>%
#   unite(a, Item, Prevalence) %>%
#   rename(Item = Parameter,
#          Prevalence = a)

d.params<-data.frame(Parameter = rep(d.tidy$Parameter, 
                               1+samples*d.tidy$Probability),
                     Item = rep(d.tidy$Item, 
                               1+samples*d.tidy$Probability),
                Prevalence = rep(d.tidy$Prevalence, 
                               1+samples*d.tidy$Probability),
                Response = rep(d.tidy$Value, 
                               1+samples*d.tidy$Probability))

# ggplot(d.params, aes(x=Response))+
#   geom_histogram()+
#   facet_grid(Item~Prevalence,scales='free')

  
  


d.summary<-d.params %>% group_by(Parameter,Item, Prevalence) %>%
  summarise(expectation = mean(Response),
              MAP = estimate_mode(Response),
            credHi = HPDhi(Response),
            credLo = HPDlo(Response))


ggplot(data=d.summary, aes(x=Parameter, y = MAP))+
  geom_bar(stat='identity', position=position_dodge())+
  geom_errorbar(aes(ymin=credLo, ymax=credHi))+
  facet_grid(Prevalence~Item, scales='free')


d.across <- d.summary %>%
  filter(Prevalence=='gamma' & Item=='response0') %>%
  ungroup() %>%
  mutate(splitHalf= expectation > median(expectation)) %>%
  mutate(splitHalf = factor(splitHalf, labels=c("distinct", "common")))

qplot(data=d.across, x=expectation, fill=splitHalf,geom='histogram')


```

Write to .csv for latex
```{r}
d.out <- d.summary %>% filter(Prevalence == 'gamma')
  d.raw <- read.csv(file='~/Documents/research/generics/manuscript/data/novelGenerics-prior-splitAccidentalFBT-trials.csv')

d.labels <- d.raw %>% rename(Parameter = stim_property) %>% select(Parameter, type)

d.table<-left_join(d.out %>% filter(Item=='response0') 
                   %>% mutate(distinctiveness = 1-MAP,
                                               distinctHigh = 1-credLo,
                                               distinctLow = 1-credHi) %>%
            ungroup() %>%
  select(-expectation,-MAP, -credLo, -credHi, -Prevalence, -Item),
          d.out %>% filter(Item=='response1') 
                %>% mutate(within = MAP,
                          withinLow = credLo,
                         withinHigh = credHi) %>%
    ungroup() %>%
  select(-expectation,-MAP, -credLo, -credHi, -Prevalence, -Item))

d.table<- left_join(unique(d.labels),d.table) %>%
  mutate(stim_type = factor(type, levels=c("part",  "color", "vague", "accidental_high", "accidental_low")))


d.table<-d.table[with(d.table, order(stim_type)),]

d.tableOut <- d.table[,c(2,1,3,4,5,6,7,8)] 

d.tableOut<-format(d.tableOut, digits=2)

d.tableOut<- d.tableOut %>% 
  unite(distinctCI,distinctLow, distinctHigh, sep=", ") %>% 
  unite(withinCI,withinLow, withinHigh, sep=", ") %>%
  unite(distinct,distinctiveness, distinctCI, sep=" [") %>% 
  unite(mcp,within, withinCI, sep=" [") %>%
  mutate(distinct = paste(distinct, "]", sep=""),
         mcp = paste(mcp, "]", sep=""))  

write.csv(d.tableOut, file='~/Documents/research/generics/manuscript/novelKinds-prevalencePrior-byItem-gammaCIs.csv', row.names=F)
```





By Type

```{r priors.byType}
d1<-read.csv("~/Documents/research/generics/manuscript/model-results/generics-asym-prior-incrmh100000a.csv")
d2<-read.csv("~/Documents/research/generics/manuscript/model-results/generics-asym-prior-incrmh100000b.csv")
d3<-read.csv("~/Documents/research/generics/manuscript/model-results/generics-asym-prior-incrmh100000c.csv")

samples = 50000
d<-bind_rows(d1,d2,d3)




d.tidy <- d

# d.tidy <- d.tidy %>%
#   unite(a, Item, Prevalence) %>%
#   rename(Item = Parameter,
#          Prevalence = a)

d.params<-data.frame(Parameter = rep(d.tidy$Parameter, 
                               1+samples*d.tidy$Probability),
                     Item = rep(d.tidy$Item, 
                               1+samples*d.tidy$Probability),
                Prevalence = rep(d.tidy$Prevalence, 
                               1+samples*d.tidy$Probability),
                Response = rep(d.tidy$Value, 
                               1+samples*d.tidy$Probability))

# ggplot(d.params, aes(x=Response))+
#   geom_histogram()+
#   facet_grid(Item~Prevalence,scales='free')


  


d.summary<-d.params %>% group_by(Parameter,Item, Prevalence) %>%
  summarise(MAP = estimate_mode(Response),
            credHi = HPDhi(Response),
            credLo = HPDlo(Response))


d.sums<- d.summary %>% filter(Prevalence=='gamma')

d.between<-d.sums %>% filter(Item=='response0') %>% 
    ungroup() %>%
                     select(-Prevalence, -Item) %>%
                               rename(MAPbetween = MAP,
                                      credLoBetween = credLo,
                                      credHiBetween = credHi)
d.within<- d.sums %>% filter(Item=='response1') %>% 
  ungroup() %>%
                                          select(-Prevalence, -Item) %>%
                               rename(MAPwithin = MAP,
                                      credLoWithin = credLo,
                                      credHiWithin = credHi)

m.join<-left_join(d.between, d.within)

m.join$Property<-factor(m.join$Parameter, 
                        levels=c("part","vague", "color", "accidental_high", "accidental_low"),
                         labels = c("body parts", "vague parts",
                                    "color parts", "common accidental",
                                    "rare accidental"))

ggplot(m.join, aes(x = MAPwithin, y = MAPbetween, color=Property))+
   geom_point(size =3)+
   geom_errorbar(aes(ymin = credLoBetween, ymax = credHiBetween),
                                 position=position_dodge(), size =1, width=0.01)+
   geom_errorbarh(aes(xmin = credLoWithin, xmax = credHiWithin),                 
                  position=position_dodge(), size =1, height=0.01)+
#  geom_text(position=position_jitter(height=0.035, width=0.0))+
  xlim(-0.05,1.05)+
  ylim(-0.05,1.05)+
  coord_fixed()+
  xlab("Within-category prevalence")+
  ylab("Between-category prevalence")+
  scale_color_brewer(palette='Set1')

#ggsave(file="~/Documents/research/generics/manuscript/figures/asymmetry-prevScatter.pdf")
#write.csv(d.out, file='~/Documents/research/generics/manuscript/model-results/asym-prior-byItem-gammaCIs.csv')

```

Reconstruct prevalence priors


```{r}
shape1 = function(gamma,delta){return (gamma * delta)}
shape2= function(gamma,delta){return ((1-gamma) * delta)}

d.samples<-data.frame()


for (i in 1:1000){

  d.samp<-d.params %>%
    group_by(Parameter,Item, Prevalence) %>%
    sample_n(1) %>%
    ungroup() %>%
    spread(Prevalence, Response) %>%
    mutate(alpha = shape1(gamma,delta),
           beta = shape2(gamma, delta)) %>%
    group_by(Parameter, Item) %>%
    mutate(prev = rbeta(1,alpha,beta),
           hasF = rbinom(1,1,prev)) %>%
    select(-gamma, -delta, -alpha, -beta) %>%
    group_by(Parameter) %>%
    summarise(prevalence = if(hasF[Item=='response0']==0) {0} 
              else {prev[Item=='response1']})
  
    d.samples<-bind_rows(d.samples, d.samp)
  
  if ((i %% 10)==0) { print(i) }
}







asym.posterior<-read.csv(file="~/Documents/research/generics/manuscript/model-results/generics-asymmetry-posteriorState-priord50iter25000_mh50000a.csv")


aysm.post.stats<- asym.posterior %>%
  filter(Parameter=='statePosterior') %>%
  group_by(Item, Prevalence) %>%
  summarize(val = sum(Value*Probability))


asym.interp<- data.frame()
for (p in levels(factor(aysm.post.stats$Item))){
  mh = data.frame(with(aysm.post.stats %>% filter(Item==p), approx(x=Prevalence, y = val, n = 100)))
  mh$Parameter  = p
  asym.interp<- bind_rows(asym.interp, mh)  
}


asym.dy <- data.frame(
                Parameter =  rep(asym.interp$Parameter, 
                                   1+samples*asym.interp$y),
                prevalence = rep(asym.interp$x,
                                   1+samples*asym.interp$y))

asym.dy$src <- "Posterior prevalence"
d.samples$src<- "Prior prevalence"

d.sampWPost = bind_rows(d.samples, asym.dy)


d.sampWPost$src<- factor(d.sampWPost$src, levels=c("Prior prevalence", "Posterior prevalence"))
d.sampWPost$Parameter<-factor(d.sampWPost$Parameter,
                       levels= c("part",
                                 "vague",
                                 "color",
                                 "accidental_high",
                                 "accidental_low"),
                       labels=c("body parts",
                                "vague parts",
                                "color parts",
                                "common accidental",
                                "rare accidental"))



color.mapping<-c(
  "#e41a1c",
"#377eb8",
"#4daf4a",
"#984ea3",
"#ff7f00"
  )

for (p in levels(d.sampWPost$Parameter)){
  
  targetcolor = color.mapping[which(p==levels(d.sampWPost$Parameter))]
  
  ggplot(d.sampWPost %>% filter(Parameter==p), 
          aes(x=prevalence,color=Parameter, 
              fill=Parameter, alpha = src, linetype=src))+
  geom_density(size=1.3, aes(y=..scaled..))+
  scale_color_manual(values=c(targetcolor))+
  scale_fill_manual(values=c(targetcolor))+
    scale_alpha_manual(values=c(0.6,0.1))+
    xlab("Prevalence")+
  ylab("Normalized density")+
 # theme_black()+
 # facet_grid(Parameter~., scales='free')+
  theme(strip.text.y=element_text(angle=0))+
    scale_x_continuous(limits=c(0,1),breaks=c(0,0.5,1))+
    scale_y_continuous(limits=c(0,1),breaks=c(0,0.5,1))+
   coord_fixed()

 
 ggsave(file=paste("~/Documents/research/generics/manuscript/figures/popout-prior-asymmetry", p, ".pdf", sep=''), width = 6, height = 3.5) 
 print(p)
}



a<-ggplot(d.samples, 
          aes(x=prevalence, color=Parameter, linetype=Parameter))+
  geom_density(size=1.3)+
  scale_color_brewer(palette='Set1')+
  xlab("Prevalence")+
  ylab("Posterior density")+
 # theme_black()+
 # facet_grid(Parameter~., scales='free')+
  theme(legend.position=c(0.7,0.65),
        strip.text.y=element_text(angle=0))+
  guides(fill=F)

b<-ggplot(d.samples %>% filter(!(prevalence==0)), 
          aes(x=prevalence, color=Parameter, linetype=Parameter))+
  geom_density(size=1.3)+
  scale_color_brewer(palette='Set1')+
  scale_x_continuous(limits=c(0,1),breaks=c(0.25,0.5,0.75,1))+
  xlab("Prevalence")+
  ylab("Posterior density")+
 # theme_black()+
  guides(color=F, linetype=F)+
  #facet_grid(Parameter~., scales='free')+
  theme(strip.text.y=element_text(angle=0))#+
 # theme(legend.position=c(0.7,0.65))

c<-arrangeGrob(a,b,nrow=1)

ggsave(c,file='~/Documents/research/generics/manuscript/figures/prior2_prevalenceprior-50kx3.pdf',width=12, height= 4)
# ggsave(a,file='~/Box Sync/talks/esslli-2015-generics/figures/prior2_prevalenceprior-50ka.pdf',width=7, height= 11)
# ggsave(b,file='~/Box Sync/talks/esslli-2015-generics/figures/prior2_prevalenceprior-50kb.pdf',width=7, height= 11)
# ggsave(b,file='~/Box Sync/talks/esslli-2015-generics/figures/prior2_prevalenceprior-50kblegend.pdf',width=5, height= 5)

```
