---
title: "natural-priors"
author: "mht"
date: "August 12, 2015"
output: html_document
---


```{r helpers}
library(coda)
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
HPDhi<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
HPDlo<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}

```


```{r}
m.path<-"~/Documents/research/generics/manuscript/model-results/"

samples = 50000
prefix<-'generics-naturalPriors-n57-incrMH100000_burn50000' 
m1<-read.csv(paste(m.path, prefix, 'a.csv', sep=''))
m2<-read.csv(paste(m.path, prefix, 'b.csv', sep=''))
m3<-read.csv(paste(m.path, prefix, 'c.csv', sep=''))

m<-bind_rows(m1,m2,m3)
#m<-read.csv(paste(m.path, prefix, 'c.csv', sep=''))

str(m)

m <- data.frame(Parameter =  rep(m$Parameter, 
                                   1+samples*m$Probability),
                Property =  rep(m$Property, 
                                   1+samples*m$Probability),
                Negation =  rep(m$Negation, 
                                   1+samples*m$Probability),
                Value = rep(m$Value, 
                                   1+samples*m$Probability))


# m.phi <- m %>% filter(Negation=='phi')
# 
# phi.summary<-m.phi %>% 
#   summarise(map = estimate_mode(Value),
#             credHi = HPDhi(Value),
#             credLo = HPDlo(Value))
# 
# write.csv(phi.summary, 
#           file='~/Documents/research/generics/manuscript/model-results/natural-priors-phi.csv')


```

```{r}
m.prev <- filter(m, Negation=='gamma')

plt1<-ggplot(m.prev, aes(x=Value))+
  #geom_histogram(binwidth=0.01,aes(y=..count../sum(..count..)))+
  geom_histogram(aes(y=..count../sum(..count..)))+
  facet_wrap(~Property, scales='free')+
  xlim(0,1)+
  xlab("Gamma")+
  ylab("Posterior probability")

#ggsave(plt1,file='~/Documents/research/generics/manuscript/figures/diagnostics/naturalPriors-gammas-allChains.pdf', width = 15, height=15)


m.prev <- filter(m, Negation=='delta')

plt2<-ggplot(m.prev, aes(x=Value))+
  #geom_histogram(binwidth=0.01,aes(y=..count../sum(..count..)))+
  geom_histogram(aes(y=..count../sum(..count..)))+
  facet_wrap(~Property, scales='free')+
  #xlim(0,50)+
  xlab("Delta")+
  ylab("Posterior probability")

# delta.summary<-m.prev %>% 
#   group_by(Property) %>%
#   summarise(map = estimate_mode(Value), 
#             credHi = HPDhi(Value),
#             credLo = HPDlo(Value))

#ggsave(plt2,file='~/Documents/research/generics/manuscript/figures/diagnostics/naturalPriors-deltas-allChains.pdf', width = 15, height=15)


m.prev <- filter(m, Negation=='prob_hasF')

plt3<-ggplot(m.prev, aes(x=Value))+
  #geom_histogram(binwidth=0.01,aes(y=..count../sum(..count..)))+
  geom_histogram(aes(y=..count../sum(..count..)))+
  facet_wrap(~Property, scales='free')+
  xlim(0,1)+
  xlab("Thetas")+
  ylab("Posterior probability")

#ggsave(plt3,file='~/Documents/research/generics/manuscript/figures/diagnostics/naturalPriors-thetas-allChains.pdf', width = 15, height=15)


```

Reconstruct prevalence prior by forward sampling

```{r}


shape1 = function(gamma,delta){return (gamma * delta)}
shape2= function(gamma,delta){return ((1-gamma) * delta)}

d.params <- m %>% filter(!(Negation=='phi')) %>%
  select(-Parameter) %>%
  rename(Parameter=Negation)


d.samples<-data.frame()


for (i in 1:100){

  d.samp<-d.params %>%
    group_by(Property, Parameter) %>%
    sample_n(1) %>%
    ungroup() %>%
    spread(Parameter, Value) %>%
    mutate(alpha = shape1(gamma,delta),
           beta = shape2(gamma, delta)) %>%
    group_by(Property) %>%
    mutate(doesHaveF = rbinom(1,1,prob_hasF)) %>%
    select(-gamma, -delta)

  
  for (k in 1:length(d.samp$Property)){
    d.iter<-data.frame(
               Pairing = d.samp[k,1],
               
               Prevalence = if (d.samp[[k,"doesHaveF"]]==1){
                                rbeta(50, d.samp[[k, "alpha"]], 
                                          d.samp[[k, "beta"]]
                                    )
                                } else {rep(0,50)}
               )
    d.samples<-bind_rows(d.samples, d.iter)
  }
  
  if ((i %% 10)==0) { print(i) }
}

#target<- c("are female", "lay eggs", "carry malaria", "have wings")
# target<- c("are male", "lay eggs", "carry malaria", "have wings")
# #ggplot(d.samples %>% filter(Prevalence!=0), 
# #ggplot(d.samples %>% filter(Property %in% target), 
# ggplot(d.samples, 
#        aes(x=Prevalence))+
#   #geom_histogram()+
#   geom_density(aes(y = ..scaled..),adjust=1, size=1, fill='grey')+
# #   geom_density(data = d.samples %>% filter((Prevalence!=0) & 
# #                                            (Property %in% target)&
# #                                              (Property!="have wings")), 
# #                aes(x=Prevalence), color='blue', linetype =2)+
#   #scale_color_brewer(palette='Dark2')+
#   xlab("Prevalence")+
#   ylab("Posterior density")+
#   theme(legend.position=c(0.7,0.65))+
#   guides(color =F)+ 
#   facet_wrap(~Property, scales='free')+
#   xlim(0,1)

#ggsave(file='~/Documents/research/generics/manuscript/figures/prevalence_priors_inferred-betas.pdf')


```



Make scatterplot: Across prevalence vs. Within prevalence

```{r scatter}

m.stats<- m %>% 
#  filter(Negation != 'delta') %>%
  group_by(Property, Negation) %>%
  summarise(MAP = estimate_mode(Value),
            credHigh = HPDhi(Value),
            credLow = HPDlo(Value))


m.spread<- m.stats %>%
  gather(key, val, MAP, credHigh, credLow) %>%
  spread(Negation, val)

m.join<- left_join(left_join(m.spread %>% 
                               filter(key=='MAP') %>% 
                               select(-key),
                   m.spread %>% 
                     filter(key=='credHigh') %>% 
                     select(-key) %>%
                     rename(credHigh_within = gamma,
                            credHigh_varianceWithin = delta,
                            credHigh_across = prob_hasF)),
                   m.spread %>% filter(key=='credLow') %>% select(-key) %>%
                     rename(credLow_within = gamma,
                            credLow_varianceWithin = delta,
                            credLow_across = prob_hasF))


m.median <- m.join %>%
  mutate(alpha = shape1(gamma,delta),
         beta = shape2(gamma,delta)) %>%

  
(m.median %>% filter(Property=='have manes'))$gamma
  
median(with(m.median %>% filter(Property=='have manes'), 
     rbeta(10000, shape1=alpha, shape2=beta)))


# m.join <- m.join %>%
#   rowwise() %>%
#   mutate(deltaX = if (delta > 2.5) {2.5} else {delta})

 m.join <- left_join(m.join, d.samples %>% filter(Prevalence!=0) %>%
  group_by(Property) %>%
  summarise(inverseRegularity = var(Prevalence)))

qplot(x=delta, geom='histogram',data= m.join, binwidth =0.5)

View(m.join %>% select(Property, gamma, deltaX, prob_hasF))

ggplot(m.join, aes(x = gamma, y = 1- prob_hasF, label=Property, color =1- inverseRegularity))+
   #geom_point(size =3, position = position_jitter(w = 0.02, h = 0.02))+
  geom_text(position = position_jitter(w = 0.00, h = 0.003))+
   #geom_errorbar(aes(ymin = 1- credLow_across, ymax = 1- credHigh_across),
  #                               position = position_jitter(w = 0.1, h = 0.1), size =1)+
   #geom_errorbarh(aes(xmin = credLow_within, xmax = credHigh_within),                 
  #                position=position_dodge(), size =1)+
 #  geom_errorbarh(aes(xmin = credLow_varianceWithin, xmax = credHigh_varianceWithin),                 
 #                 position=position_dodge(), size =1)+
  #  geom_text(position=position_jitter(height=0.035, width=0.0))+
  xlim(-0.05,1.2)+
#ylim(-0.05,1.05)+
 # coord_fixed()+
  #coord_flip()+
    scale_color_gradient(low='#999999', high ='#ef8a62')

, limits=c(0,1),
                       breaks=c(0,0.5,1))+
  #xlab("Within-category prevalence")+
  #ylab("Between-category prevalence")


ggplot(m.join, aes(x = gamma, y = 1-prob_hasF, label=Property))+
   geom_point(size =2.5, color='black')+
   geom_errorbar(aes(ymin = 1-credLow_across, ymax = 1-credHigh_across),
                                 position=position_dodge(), size =1,
                 color='black')+
   geom_errorbarh(aes(xmin = credLow_within, xmax = credHigh_within),                 
                  position=position_dodge(), size =1,
                  color='black')+
#  geom_text(position=position_jitter(height=0.035, width=0.0))+
  xlim(-0.05,1.05)+
  ylim(-0.05,1.05)+
  coord_fixed()+
  xlab("\n Mean conditional prevalence")+
  ylab("Property distinctiveness \n")

ggsave(file='~/Documents/research/generics/manuscript/figures/prevalences-scatter-1.pdf', width=12, height=6)




#+
#  theme_blackDisplay()


#ggsave(file=paste('~/Box Sync/talks/lightning-2015-generics/prevalence-scatter.pdf',sep=''), 
#       width=8, height=6)



```



Add posterior thresholds to prevalence prior plots

```{r}

prefix<-'generics-truthJudgment-wState-previter10000_prevprioriter10000-priord50Zero-n57_mh50000_burn25000'

t<-read.csv(paste(m.path, prefix, 'c.csv', sep=''))


t.tidy <- t %>%
  #filter(Parameter=='thetaPosterior' & Property %in% target) %>%
  filter(Parameter=='statePosterior') %>%
  select(-Negation, -Parameter) %>%
  rename(bin = Category)


t.dy <- data.frame(
                Property =  rep(t.tidy$Property, 
                                   1+samples*t.tidy$Probability),
                bin =  rep(t.tidy$bin,
                                   1+samples*t.tidy$Probability),
                Value = rep(t.tidy$Value, 
                                   1+samples*t.tidy$Probability))

t.stats<- t.dy %>%
  group_by(Property, bin) %>%
  summarize(MAP = estimate_mode(Value),
            credLow = HPDlo(Value),
            credHigh = HPDhi(Value)) %>%
    mutate(bin = to.n(bin)) %>%
  group_by(Property) %>%
  mutate(cdf = cumsum(MAP)) %>%
  mutate(cdfLow = cdf - (MAP-credLow),
         cdfHigh = cdf + (credHigh - MAP)) 
  

t.interp<- data.frame()
for (p in levels(t.stats$Property)){
  mh = data.frame(with(t.stats 
                       %>% filter(Property==p), 
                       approx(x=bin, y = MAP, n = 100)))
  mh$Property  = p
  t.interp<- bind_rows(t.interp, mh)  
}


t.dy <- data.frame(
                Property =  rep(t.interp$Property, 
                                   1+samples*t.interp$y),
                Prevalence = rep(t.interp$x,
                                   1+samples*t.interp$y))


t.dy$src= "Posterior prevalence"
d.samples$src<- "Prior prevalence"

d.sty <- bind_rows(t.dy, d.samples)
# t.stats %>% filter(Property=='are male')
# 
target<- c("are female", "lay eggs", "carry malaria", "have wings",
           "dont attack swimmers")

d.sty$src<-factor(d.sty$src, levels=c("Prior prevalence", "Posterior prevalence"))


m.prevTargets <- m.summary %>%
  filter(Category%in%c("Robins", "Mosquitos", 
                       "Ducks", "Sharks") )

m.prevTargets <- m.prevTargets[c(1,5,7, 10,11),]

for (t in target){
#  ggplot(d.samples %>% filter(Property == t), 
#          aes(x=Prevalence))+
   ggplot(d.sty%>% filter(Property == t), 
          aes(x=Prevalence, linetype=src, color=src, alpha=src))+
    geom_density(aes(y=..scaled..), size=1, color ='black',
                 fill='black')+
       scale_color_manual(values=c("#bdbdbd","#f0f0f0"))+
  scale_alpha_manual(values=c(0.6,0.1))+
    #geom_density(size=1, alpha=0.7)+
     geom_errorbarh(data = m.prevTargets %>% filter(Property==t),
                    aes(x= map, xmin = credLow, xmax = credHigh,
                    y = 1.05), color='#2ca25f', size = 1.1,
                    height = 0.1, inherit.aes=F)+
     #  scale_linetype_manual(values = c(1, 3))+
  #geom_histogram()+
#    geom_dens  ity(data=t.stats %>% filter(Property == t),
#                 aes(x=bin, y=MAP), size =1,
#                 stat='identity')+
#   geom_density(aes(y = ..scaled..), size=1, linetype =3)+
  #  geom_density(size=1, linetype =3)+
  #geom_bar(data = t.stats, 
  #             aes(x=as.numeric(bin), y =MAP), stat='identity')+
  #scale_color_brewer(palette='Dark2')+
  scale_linetype_manual(values=c(1,2))+
 # theme_blackDisplay()+
  xlab("Prevalence")+
  #theme(legend.position=c(0.7,0.65))+
  #guides(color =F)+ 
  guides(fill=F, color=F, alpha=F, linetype=F)+
  facet_wrap(~Property, scales='free')+
  scale_x_continuous(limits=c(0,1), breaks=c(0,0.5,1))+
  scale_y_continuous(limits=c(0,1.1), breaks=c(0,0.5,1))+
  ylab("Scaled density")+
 # theme(axis.text.x=element_text(size=20),
#        axis.title.x = element_text(size=24),
#        strip.text.x = element_text(size=24))
  theme(#axis.text.y=element_blank(),
        strip.text.x=element_text(size=16))+
  coord_fixed()
    

ggsave(file=paste('~/Documents/research/generics/manuscript/figures/truthjudge-prevalences-priors-posteriors-wTarget-',t,'.pdf',sep=''), 
       width=5, height=3.5)

print(t)
#ggsave(file=paste('~/Box Sync/talks/lightning-2015-generics/truthjudge-prevalences-priors-posteriors',t,'.pdf',sep=''), 
#       width=7, height=4)


}


# 
# 
# ggplot(t.stats, aes(x=bin, y= MAP))+
#   #geom_line() + 
#    geom_density(stat='identity')+
#   #geom_smooth(aes(ymin=credLow, ymax=credHigh), stat='identity')+
#   facet_wrap(~Property, scales='free')+
#   ylim(-0.05,1.05)
# 
# 
# 
# 
# ggplot(t.stats, aes(x=bin, y= cdf))+
#   #geom_line() + 
#   geom_density(stat='identity')+
# #  geom_smooth(aes(ymin=cdfLow, ymax=cdfHigh), stat='identity')+
#   facet_wrap(~Property, scales='free')+
#   ylim(-0.05,1.05)



```


