---
title: "schematic-priors"
author: "mht"
date: "May 2, 2016"
output: html_document
---

Schematic priors and posteriors for paper.

```{r}
library(rwebppl)
```

```{r webppl.model}
rsa<-"
// discretized range between 0 - 1
// var bins = [0.001,0.01,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.99, 0.999]
var bins = [0.001,0.01,0.05, 0.1,0.15, 0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,0.7,0.75,0.8,0.85,0.9,0.95,0.99, 0.999]

var marginalize = function(myERP, label){
    Enumerate(function(){
        var x = sample(myERP)
        return x[label]
    })
}

// function returns a discretized beta PDF
var discretizeBeta = function(g, d){
  var shape_alpha =  g * d;
  var shape_beta = (1-g) * d;
  var betaPDF = function(x){
    return Math.pow(x,shape_alpha-1)*Math.pow((1-x),shape_beta-1)
  }
  return map(betaPDF, bins)
}

var discretizeBetaStandard = function(shape_alpha, shape_beta){
  var betaPDF = function(x){
    return Math.pow(x,shape_alpha-1)*Math.pow((1-x),shape_beta-1)
  }
  return map(betaPDF, bins)
}

var s1optimality = 20
var thresholdBins = [0.001,0.01,0.05, 0.1,0.15, 0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,0.7,0.75,0.8,0.85,0.9,0.95,0.99]
var thresholdPrior = function() {
  var threshold = uniformDraw(thresholdBins)
  return threshold
}

var utterancePrior = function() {
  var utterances = ['generic', 'mu']  
  //    var utterances = ['generic is true',
  //                 'generic is false']  
  return uniformDraw(utterances)
  //return utterances[discrete([1,1])]
}

var meaning = function(utt,state, threshold) {
//var meaning = function(utt,state, threshold, threshold2) {
  return _.isNumber(utt) ? state == utt :
  utt=='generic'? state>threshold :
 // utt=='not generic' ? state<threshold2 :
  utt=='specific'? state==0.001 :
  utt=='generic is false'? state<=threshold :
  utt=='mu'? true:
  utt=='some'? state>0:
  utt=='most'? state>= 0.5:
  utt=='all'? state >= 0.99:
  true
}

var listener0 = cache(function(utterance, threshold, params) {
  Enumerate(function(){
    var causeIsPresent = flip(params.theta)
    var state = causeIsPresent ? 
        bins[discrete(discretizeBeta(params.g1,params.d1))] : 
        bins[discrete(discretizeBeta(params.g0,params.d0))]

    var m = meaning(utterance, state, threshold)
    condition(m)
    return state
  })
})

var speaker1 = function(state, threshold,params) {
  Enumerate(function(){
    var utterance = utterancePrior()
    var L0 = listener0(utterance, threshold, params)
    factor(s1optimality*L0.score([],state))
    return utterance
  })
}


var listener1 = function(utterance, params) {
  Enumerate(function(){
    var causeIsPresent = flip(params.theta)
    var state = causeIsPresent ? 
        bins[discrete(discretizeBeta(params.g1,params.d1))] : 
        bins[discrete(discretizeBeta(params.g0,params.d0))]

    var threshold = thresholdPrior()
    //var threshold2 = thresholdPrior()
    var S1 = speaker1(state, threshold, params)
    factor(S1.score([],utterance))
    return {state: state,
            threshold: threshold}
  })
}


var speaker2 = function(prevalence, prior){
  Enumerate(function(){
    var utterance = utterancePrior()
    var wL1 = listener1(utterance, prior)
    factor(wL1.score([], prevalence))
    return utterance
  })
}

var thePrior = Enumerate(function(){
  return flip(myPrior[0].theta) ? 
          bins[discrete(discretizeBeta(myPrior[0].g1,myPrior[0].d1))] :
          bins[discrete(discretizeBeta(myPrior[0].g0,myPrior[0].d0))]
})

var l1post = listener1('generic', myPrior[0])

var output = {
  prior: thePrior, 
  priorTheta: Enumerate(function(){return thresholdPrior()}),
  l1state: marginalize(l1post, 'state'), 
  l1theta: marginalize(l1post, 'threshold')
}
output
"
```

Run model for many different priors


Kinds of bimodal priors:

1. 50 / 50 mixture: delta + concave
2. 50 / 50 mixture: delta + uniform
3. 50 / 50 mixture: delta + left-centered-concave

```{r}
my_priors <- data.frame(
  label= c("uniform", "convex", "concave", 
           "uniform2", "convex2", "concave2"),
  theta = c(1, 1, 1, 0.5, 0.5, 0.5),
  g1 = c(1, 3, 5, 1, 0.5, 5),
  d1 = c(1, 0.2, 5, 1, 0.5, 5),
  g0 = c(0,0,0,0.2,0.2,0.01),
  d0 = c(0,0,0,0.8,0.8,0.8)
)
#my_prior = my_priors[1,]

my_priors <- droplevels(my_priors %>%
                          filter(label%in%c('convex','convex2')))
,
                                            'concave', 'concave2')))

model_results<-data.frame()
for (i in levels(my_priors$label)){
  
  my_prior <- my_priors %>% filter(label==i)

  temp_post<-webppl(model_code=rsa, data =my_prior, 
                    data_var = "myPrior")
  
  model_results<-bind_rows(
    model_results,
      bind_cols(
        data.frame(priorLabel = rep(i,  length(temp_post$prior$support))),
        left_join(
         left_join(
            left_join(
              data.frame(temp_post$prior) %>% rename(prior = probs),
              data.frame(temp_post$l1state) %>% rename(l1state = probs)
              ),
            data.frame(temp_post$l1theta) %>% rename(l1theta = probs)
         ),
        data.frame(temp_post$priorTheta) %>% rename(priorTheta = probs)
        ) %>% select(support, prior, l1state, l1theta, priorTheta)
      )
    )
  print(i)
}

``` 

Plot the results 

```{r plot}
plot.path <- "~/Documents/research/generics/manuscript/figures/"

model_results %>% 
  gather(key, val, prior, l1state, l1theta, priorTheta) %>%
  mutate(key = factor(key, 
                      levels=c("l1state", "l1theta", "prior", "priorTheta"), 
                      labels=c("Posterior Prevalence", "Posterior Threshold",
                               "Prior Prevalence","Prior Threshold"))) %>%
  separate(key, c("Distribution","Parameter")) %>%
  ggplot(., aes(x=support, y=val, 
                color=Parameter, 
                linetype=Distribution, 
                #fill=Parameter, 
                #alpha=Distribution
                ))+
  #geom_point()+
  #geom_smooth(se=F, method="loess")+
  geom_line(size=1.2)+
  #geom_density(stat='identity', size = 1.2)+
  scale_linetype_manual("",values = c(1, 4))+
  scale_color_brewer("", palette='Set1')+
  #scale_alpha_manual(values=c(0.7, 0.4))+
  facet_wrap(~priorLabel)+
  ylab("Probability")+
  xlab("Prevalence")+
  theme_paper()+
   theme(strip.background = element_blank(),
       strip.text.x = element_blank())

#ggsave(paste(plot.path, "schematic-uniform.pdf",sep=''), width = 12, height = 5)



```


